# Пользователи
## Регистрация пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "adminn@mail.ru",
  "userName": "admin",
  "password": "adminn",
  "isAdmin": "true"
}

###

## Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "emily@overlook.net",
  "password": "123456"
}

###

## Проверка токена пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVtaWx5QG92ZXJsb29rLm5ldCIsImlkIjoiNjQ3YTM4NzA5NTZmNGNhZDI2NTRjODIxIiwiaWF0IjoxNjg1NzMyNTU4LCJleHAiOjE2ODU5MDUzNTh9.v3DREakxtIe8Q61DNzlL4oYFnG0ku9y7dzxNp0J5wfo

###

# Товары
## Товары по идентификатору

GET http://localhost:5000/guitars/647a16172bef96e32e60eb3b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWlubkBtYWlsLnJ1IiwiaWQiOiI2NDdiNmZkNzIxZTg3ZDViYTE2ZGZhMmUiLCJpYXQiOjE2ODU4MTE4MTgsImV4cCI6MTY4NTk4NDYxOH0.WjiClZEO7FSUDkRRkLyy3dTW-BWiDiR73SlEbPT588E

###

## Список товаров

GET http://localhost:5000/guitars?sortType=price-down&&guitarType=укулеле HTTP/1.1

###

## Создание товара

POST http://localhost:5000/guitars HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWlubkBtYWlsLnJ1IiwiaWQiOiI2NDdiNmZkNzIxZTg3ZDViYTE2ZGZhMmUiLCJpYXQiOjE2ODU4MTE4MTgsImV4cCI6MTY4NTk4NDYxOH0.WjiClZEO7FSUDkRRkLyy3dTW-BWiDiR73SlEbPT588E

{
  "name": "VESTON F-38/BK",
  "description": "VESTON F-38/BK - акустическая гитара в корпусе фолк отличного качества, доступная по демократичной цене. Такая гитара будет отличным выбором для начинающих музыкантов и обучающихся игре на инструменте.",
  "image": "2.png",
  "guitarType": "укулеле",
  "articleNumber": "A073576",
  "stringAmount": 4,
  "price": 10100
}

###

## Удаление товара

DELETE http://localhost:5000/guitars/647a1287a4bb9b0915643bf0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWlubkBtYWlsLnJ1IiwiaWQiOiI2NDdiNmZkNzIxZTg3ZDViYTE2ZGZhMmUiLCJpYXQiOjE2ODU4MTE4MTgsImV4cCI6MTY4NTk4NDYxOH0.WjiClZEO7FSUDkRRkLyy3dTW-BWiDiR73SlEbPT588E

###

## Обновление товара

PATCH http://localhost:5000/guitars/647a1287a4bb9b0915643bf0 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWlubkBtYWlsLnJ1IiwiaWQiOiI2NDdiNmZkNzIxZTg3ZDViYTE2ZGZhMmUiLCJpYXQiOjE2ODU4MTE4MTgsImV4cCI6MTY4NTk4NDYxOH0.WjiClZEO7FSUDkRRkLyy3dTW-BWiDiR73SlEbPT588E

{
  "price": 1000
}

###
